---
- name: Create container
  docker_container:
     name: webserver
     image: nginx:latest
     state: started
     ports: 
       - "80:80"
       - "433:433"

#- name: Wait for "30" sec for container to be started 
#  wait_for: timeout=30



#- name: Copy the html to the main host
#  copy:
#    src: "./files/site/"
#    dest: "/usr/share/nginx/html/"


- name: Copy html to container
  command: docker cp /usr/share/nginx/html/ webserver:/usr/share/nginx/
  become: yes  

- name: Copy nginx conf to host
  copy:
    src: "./files/default.conf"
    dest: "/etc/nginx/conf.d/"
    force: yes

- name: Copy nginx conf to container
  command: docker cp /etc/nginx/conf.d/default.conf webserver:/etc/nginx/conf.d/default.conf
  become: yes

#    notify: 'restart-docker-nginx'

#     volumes:
#       - /home/ivani/ansible/roles/container/templates/index.html:/usr/share/nginx/html/:ro
#       - /home/ivani/ansible/roles/container/templates/templates/default.conf

